import {
  handleClearActivityMessage,
  handleDebug,
  handleGetCurrentActivity,
  handleGetDebug,
  handleActivityUpdateMessage,
  handleSetPresencePause,
} from "@/background/router/handlers/activity.handlers"
import {
  handleGetAnalyticsConsent,
  handleSetAnalyticsConsent,
  handleTrackEvent,
  handleGetRuntimeLogs,
  handleClearRuntimeLogs,
} from "@/background/router/handlers/analytics.handlers"
import { handleGetDiagnostic } from "@/background/router/handlers/diagnostics.handlers"
import {
  handleConnectNative,
  handleGetNativeStatus,
  handleGetUserScriptsStatus,
  handleRestartNative,
} from "@/background/router/handlers/native.handlers"
import {
  handleCheckUpdates,
  handleClearSnooze,
  handleFetchCatalog,
  handleGetInstallQueue,
  handleGetPresenceSettings,
  handleGetPresences,
  handleInstall,
  handleInstallFromApi,
  handleInstallLocalZip,
  handleRetryInstallQueue,
  handleSetPresenceSettings,
  handleSetSchedule,
  handleSnooze,
  handleToggle,
  handleUninstall,
  handleUpdate,
} from "@/background/router/handlers/presences.handlers"
import { handleGetSettings, handleResetOnboardingForDev, handleSetSettings } from "@/background/router/handlers/settings.handlers"
import type { HandlerRegistry } from "@/background/router/router"

export const buildHandlerRegistry = (): HandlerRegistry => ({
  GET_PRESENCES: handleGetPresences,
  GET_NATIVE_STATUS: handleGetNativeStatus,
  GET_USER_SCRIPTS_STATUS: handleGetUserScriptsStatus,
  GET_DIAGNOSTIC: handleGetDiagnostic,
  CONNECT_NATIVE: handleConnectNative,
  RESTART_NATIVE: handleRestartNative,
  GET_CURRENT_ACTIVITY: handleGetCurrentActivity,
  GET_DEBUG: handleGetDebug,
  TOGGLE_PRESENCE: handleToggle,
  UNINSTALL_PRESENCE: handleUninstall,
  ACTIVITY_UPDATE: handleActivityUpdateMessage,
  CLEAR_ACTIVITY: handleClearActivityMessage,
  INSTALL_PRESENCE: handleInstall,
  UPDATE_PRESENCE: handleUpdate,
  INSTALL_PRESENCE_FROM_API: handleInstallFromApi,
  INSTALL_LOCAL_PRESENCE_ZIP: handleInstallLocalZip,
  FETCH_PRESENCE_CATALOG: handleFetchCatalog,
  SET_PRESENCE_PAUSE: handleSetPresencePause,
  GET_INSTALL_QUEUE: handleGetInstallQueue,
  RETRY_INSTALL_QUEUE: handleRetryInstallQueue,
  CHECK_UPDATES: handleCheckUpdates,
  GET_SETTINGS: handleGetSettings,
  SET_SETTINGS: handleSetSettings,
  GET_ANALYTICS_CONSENT: handleGetAnalyticsConsent,
  SET_ANALYTICS_CONSENT: handleSetAnalyticsConsent,
  RESET_ONBOARDING_FOR_DEV: handleResetOnboardingForDev,
  GET_PRESENCE_SETTINGS: handleGetPresenceSettings,
  SET_PRESENCE_SETTINGS: handleSetPresenceSettings,
  SNOOZE_PRESENCE: handleSnooze,
  CLEAR_SNOOZE: handleClearSnooze,
  SET_PRESENCE_SCHEDULE: handleSetSchedule,
  GET_RUNTIME_LOGS: handleGetRuntimeLogs,
  CLEAR_RUNTIME_LOGS: handleClearRuntimeLogs,
  TRACK_EVENT: handleTrackEvent,
  DEBUG: handleDebug,
})
