import react from "@vitejs/plugin-react"
import "dotenv/config"
import { fetchBrandIcons } from "./fetch-brand-icons"
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "fs"
import { dirname, join, resolve } from "path"
import { fileURLToPath } from "url"
import { build } from "vite"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")

const BROWSER = (process.argv[2] ?? "chrome") as "chrome" | "firefox"
const DIST = join(ROOT, "dist", BROWSER)

const webBaseUrl = process.env.VITE_WEB_BASE_URL ?? "https://nowly.me"
const apiBaseUrl = process.env.VITE_API_BASE_URL ?? "https://api.nowly.me"
const cdnBaseUrl = process.env.VITE_CDN_BASE_URL ?? "https://cdn.nowly.me"

const define = {
  "import.meta.env.VITE_WEB_BASE_URL": JSON.stringify(webBaseUrl),
  "import.meta.env.VITE_API_BASE_URL": JSON.stringify(apiBaseUrl),
  "import.meta.env.VITE_CDN_BASE_URL": JSON.stringify(cdnBaseUrl),
  "import.meta.env.BROWSER": JSON.stringify(BROWSER),
}

rmSync(DIST, { recursive: true, force: true })
mkdirSync(DIST, { recursive: true })

const buildPage = async (name: string, source = name) => {
  await build({
    root: join(ROOT, "src", source),
    base: "./",
    plugins: [react()],
    define,
    resolve: {
      alias: {
        "@": resolve(ROOT, "src"),
        "@messages": resolve(ROOT, "messages"),
      },
    },
    build: {
      outDir: join(DIST, name),
      emptyOutDir: true,
      rollupOptions: { input: join(ROOT, "src", source, "index.html") },
    },
    configFile: false,
  })
}

const buildScript = async (name: string, entry: string) => {
  await build({
    root: ROOT,
    define,
    resolve: {
      alias: {
        "@": resolve(ROOT, "src"),
        "@messages": resolve(ROOT, "messages"),
      },
    },
    build: {
      outDir: DIST,
      emptyOutDir: false,
      lib: {
        entry,
        formats: ["iife"] as const,
        name: `__presences_${name}`,
        fileName: () => `${name}.js`,
      },
      rollupOptions: {
        external: [],
      },
    },
    configFile: false,
  })
}

const copyManifest = () => {
  const manifest = JSON.parse(readFileSync(join(ROOT, "manifest.json"), "utf-8"))

  // Common mutations for all browsers
  manifest.content_scripts[0].js = ["content.js"]
  manifest.icons = {
    16: "icons/icon16.png",
    48: "icons/icon48.png",
    128: "icons/icon128.png",
  }
  manifest.action.default_icon = { ...manifest.icons }
  delete manifest.key

  if (BROWSER === "firefox") {
    manifest.background = { scripts: ["background.js"] }
    delete manifest.minimum_chrome_version
    // userScripts is an optional-only permission on Firefox — declare it in optional_permissions
    // and request it at runtime (Firefox 136+ MV3 userScripts API).
    manifest.permissions = manifest.permissions
      .filter((p: string) => p !== "userScripts" && p !== "sidePanel")
    manifest.optional_permissions = [...(manifest.optional_permissions ?? []), "userScripts"]
    delete manifest.side_panel
    delete manifest.action.default_popup
    manifest.sidebar_action = {
      default_icon: manifest.icons,
      default_panel: "sidepanel/index.html",
      default_title: "__MSG_extensionName__",
    }
    if (manifest.commands?.["open-side-panel"]) {
      manifest.commands._execute_sidebar_action = {
        suggested_key: manifest.commands["open-side-panel"].suggested_key,
        description: manifest.commands["open-side-panel"].description,
      }
      delete manifest.commands["open-side-panel"]
    }
    if (manifest.commands?._execute_action) {
      delete manifest.commands._execute_action
    }
    manifest.browser_specific_settings = {
      gecko: {
        id: "nowly@nowly.me",
        strict_min_version: "136.0",
        // Required by AMO — declare data collection practices.
        // "none" = nothing collected/transmitted. Update if that changes.
        data_collection_permissions: { required: ["none"] },
      },
    }
  } else {
    manifest.background.service_worker = "background.js"
    delete manifest.background.type
    delete manifest.action.default_popup
    manifest.side_panel.default_path = "sidepanel/index.html"
  }

  writeFileSync(join(DIST, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`)
}

const resetGeneratedPresences = () => {
  const generatedDir = join(ROOT, "src", "generated")
  const placeholderFile = join(generatedDir, "bundled-presences.ts")
  mkdirSync(generatedDir, { recursive: true })
  writeFileSync(placeholderFile, [
    '// Auto-generated by build.ts - store builds must not include bundled presences',
    'import type { PresenceRelease } from "@/shared/types"',
    '',
    'export interface BundledPresence {',
    '  slug: string',
    '  release: PresenceRelease',
    '}',
    '',
    'export const BUNDLED_PRESENCES: BundledPresence[] = []',
    '',
    'export const BUNDLED_PRESENCE_SLUGS: string[] = []',
    '',
  ].join("\n"))
  writeFileSync(join(generatedDir, "bundled-presence-slugs.ts"), [
    '// Auto-generated by build.ts - store builds must not include bundled presences',
    'export const BUNDLED_PRESENCE_SLUGS: string[] = []',
    '',
  ].join("\n"))
}

const copyStatic = async () => {
  cpSync(join(ROOT, "_locales"), join(DIST, "_locales"), { recursive: true })
  try {
    await fetchBrandIcons(join(DIST, "icons"))
  } catch (error) {
    console.warn("  ⚠ Could not fetch brand icons from CDN — load the unpacked build anyway.", error)
  }
}

resetGeneratedPresences()

await buildPage("sidepanel", "entrypoints/sidepanel")
await buildScript("background", join(ROOT, "src", "entrypoints", "background", "index.ts"))
await buildScript("content", join(ROOT, "src", "entrypoints", "content", "index.ts"))
copyManifest()
await copyStatic()
