import { createHash } from "crypto"
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs"
import { join } from "path"
import { ROOT } from "./config"

const WEBSITES_PRESENCES = join(ROOT, "..", "..", "packages", "presences", "dist", "presences")
const GENERATED_DIR = join(ROOT, "src", "generated")

const canonicalJson = (value: unknown): string => {
  if (value === null || typeof value !== "object") return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`
  const object = value as Record<string, unknown>
  return `{${Object.keys(object)
    .filter((key) => object[key] !== undefined)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalJson(object[key])}`)
    .join(",")}}`
}

const sha256Base64Url = (input: string): string => createHash("sha256").update(input).digest().toString("base64url")

const writeGenerated = (slugs: string[], entries: unknown[], banner: string): void => {
  mkdirSync(GENERATED_DIR, { recursive: true })
  writeFileSync(
    join(GENERATED_DIR, "bundled-presences.ts"),
    `// ${banner}\nimport type { PresenceRelease } from "@/shared/types"\n\nexport interface BundledPresence {\n  slug: string\n  release: PresenceRelease\n}\n\nexport const BUNDLED_PRESENCES: BundledPresence[] = ${JSON.stringify(entries, null, 2)}\n`,
  )
  writeFileSync(
    join(GENERATED_DIR, "bundled-presence-slugs.ts"),
    `// ${banner}\nexport const BUNDLED_PRESENCE_SLUGS: string[] = ${JSON.stringify(slugs)}\n`,
  )
}

const BANNER = "Auto-generated by scripts/bundle-presences.ts - do not edit manually"

export const resetBundledPresences = (): void => writeGenerated([], [], `${BANNER} (store builds ship none)`)

export const generateBundledPresences = (): void => {
  const entries: { slug: string; release: unknown }[] = []

  if (!existsSync(WEBSITES_PRESENCES)) {
    console.warn("  ⚠ No presences found - building extension without bundled presences")
  } else {
    for (const dir of readdirSync(WEBSITES_PRESENCES, { withFileTypes: true }).filter((d) => d.isDirectory())) {
      const slug = dir.name
      const bundlePath = join(WEBSITES_PRESENCES, slug, "bundle.js")
      const metadataPath = join(WEBSITES_PRESENCES, slug, "metadata.json")
      if (!existsSync(bundlePath) || !existsSync(metadataPath)) continue

      const bundle = readFileSync(bundlePath, "utf-8")
      const metadata: Record<string, unknown> = { ...JSON.parse(readFileSync(metadataPath, "utf-8")), slug }
      const settingsPath = join(WEBSITES_PRESENCES, slug, "settings.json")
      if (existsSync(settingsPath)) metadata.settings = JSON.parse(readFileSync(settingsPath, "utf-8"))

      entries.push({
        slug,
        release: {
          slug,
          version: metadata.version ?? `0.0.0-dev.${Date.now()}`,
          metadata,
          bundle,
          sha256: sha256Base64Url(bundle),
          metadataHash: sha256Base64Url(canonicalJson(metadata)),
          signature: "",
          signedAt: new Date().toISOString(),
        },
      })
    }
  }

  writeGenerated(entries.map((e) => e.slug), entries, BANNER)
  console.log(`  ✔ Bundled ${entries.length} presences`)
}

export const copyPresenceAssets = (distDir: string): void => {
  if (!existsSync(WEBSITES_PRESENCES)) return

  let count = 0
  for (const dir of readdirSync(WEBSITES_PRESENCES, { withFileTypes: true }).filter((d) => d.isDirectory())) {
    const assetsSrc = join(WEBSITES_PRESENCES, dir.name, "assets")
    if (!existsSync(assetsSrc)) continue
    cpSync(assetsSrc, join(distDir, "presences", dir.name, "assets"), { recursive: true })
    count++
  }
  if (count > 0) console.log(`  ✔ Copied assets for ${count} presences`)
}
