// Selective re-export of the Remix Icons actually used in the extension,
// matching apps/web/packages/ui's iconography (RiXxxLine, Fill for active
// states). Replaces the old @tabler/icons-react re-exports in tmp/src/lib/tabler-icons.ts.
export {
  RiAddLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowUpDownLine,
  RiArrowUpSLine,
  RiBarChart2Line,
  RiBox3Line,
  RiCalendarLine,
  RiCheckboxCircleFill,
  RiCheckboxCircleLine,
  RiCheckLine,
  RiClipboardLine,
  RiCloseCircleLine,
  RiCloseLine,
  RiComputerLine,
  RiDeleteBinLine,
  RiDiscLine,
  RiDiscordFill,
  RiDownload2Line,
  RiExternalLinkLine,
  RiFileCopyLine,
  RiFileZipLine,
  RiFocus3Line,
  RiGithubFill,
  RiGlobalLine,
  RiHeartLine,
  RiHomeLine,
  RiInformationLine,
  RiLayoutGridLine,
  RiListUnordered,
  RiLoader2Line,
  RiLockLine,
  RiMoonLine,
  RiMoreLine,
  RiNodeTree,
  RiPaletteLine,
  RiPauseLine,
  RiPlayLine,
  RiPuzzle2Line,
  RiRefreshLine,
  RiRestartLine,
  RiSettings3Line,
  RiShoppingBag3Line,
  RiSnowflakeLine,
  RiSubtractLine,
  RiSunLine,
  RiTerminalLine,
  RiTimeLine,
  RiTranslate2,
  RiYoutubeFill,
} from "@remixicon/react"
