process.env.SKIP_ENV_VALIDATION ??= "true"
process.env.JWT_SECRET ??= "test-jwt-secret"
process.env.ANONYMOUS_HASH_SECRET ??= "test-anonymous-hash-secret"
process.env.DISCORD_CLIENT_ID ??= "test-discord-client-id"
process.env.DISCORD_CLIENT_SECRET ??= "test-discord-client-secret"
process.env.DISCORD_REDIRECT_URI ??= "http://localhost:3001/auth/discord/callback"
process.env.PRESENCE_SIGNING_PRIVATE_KEY ??= "test-presence-signing-private-key"
